Repository hashicorp/packer-plugin-sdk, pull requests merged in 2022-08, with the labels that each got.

#122 Update Xcode version for Darwin test builds
  .circleci/config.yml
Labels: tech-debt

#124 communicator: fix SSH config typo
  cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
  communicator/config.go
Labels: documentation, docs

#121 sdk: Bump SDK to Go 1.18
  .circleci/config.yml
  Makefile
  go.mod
  go.sum
Labels: enhancement
