Repository hashicorp/packer-plugin-sdk, pull requests merged in 2022-09, with the labels that each got.

#115 Fix possibility to use forward slashes with nested folders in cd_files for Windows
  multistep/commonsteps/step_create_cdrom.go
  multistep/commonsteps/step_create_cdrom_test.go
Labels: bug

#101 Provision SSHPublicKey while use custom SSH Private key
  communicator/sshkey/pubkey.go
  communicator/sshkey/pubkey_test.go
  communicator/step_ssh_keygen.go
Labels: enhancement

#129 Update release version v0.3.2
  version/version.go
Labels: tech-debt
