Repository hashicorp/packer-plugin-sdk, pull requests merged in 2023-07, with the labels that each got.

#191 Remove extra backticks from HTTP server documentation
  cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/HTTPConfig.mdx
  multistep/commonsteps/http_config.go
Labels: docs

#190 [HPR-1190] Add `packer-sdc fix` command
  cmd/packer-sdc/README.md
  cmd/packer-sdc/internal/fix/README.md
  cmd/packer-sdc/internal/fix/cmd.go
  cmd/packer-sdc/internal/fix/fix.go
  cmd/packer-sdc/internal/fix/gocty.go
  cmd/packer-sdc/internal/fix/gocty_test.go
  cmd/packer-sdc/internal/fix/testdata/empty/go.mod
  cmd/packer-sdc/internal/fix/testdata/fixed/basic/go.mod
  cmd/packer-sdc/internal/fix/testdata/fixed/many-replace/go.mod
  cmd/packer-sdc/internal/fix/testdata/invalid/go.mod
  cmd/packer-sdc/internal/fix/testdata/missing-requires/both/go.mod
  cmd/packer-sdc/internal/fix/testdata/missing-requires/go-cty/go.mod
  cmd/packer-sdc/internal/fix/testdata/missing-requires/packer-plugin-sdk/go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/basic/fixed.go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/basic/go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/many-replace/fixed.go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/many-replace/go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/version/fixed.go.mod
  cmd/packer-sdc/internal/fix/testdata/unfixed/version/go.mod
  cmd/packer-sdc/main.go
  go.mod
  go.sum
Labels: enhancement

#194 Fix diff header for fix command
  cmd/packer-sdc/internal/fix/cmd.go
Labels: enhancement

#195 Update pinned actions to latest trusted versions
  .github/workflows/actionlint.yml
  .github/workflows/go-test.yml
  .github/workflows/release.yml
Labels: tech-debt, SEC-090/Pinning/Trusted

#196 Cut release v0.5.0
  version/version.go
Labels: breaking-change
