Repository hashicorp/packer-plugin-sdk, pull requests merged in 2024-06, with the labels that each got.

#242 Makefile: replace enumer upstream with dmarkham's
  Makefile
  communicator/sshkey/algorithm_enumer.go
Labels: tech-debt, dependencies

#243 communicator: fix reference to ssh_method in docs
  cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
  communicator/config.go
Labels: docs

#248 Bump dependencies to address govulncheck reported vulnerabilities
  go.mod
  go.sum
Labels: dependencies

#252 .goreleaser.yml: Update configuration to v2
  .goreleaser.yml
Labels: tech-debt
